title: Recode Project
author:
  name: Recode Team

description: >
  The ReCode Project is a community-driven effort to preserve computer art by translating it into a modern programming language. Every translated work is available to the public and contemporary artists to learn from, share, and build on.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:title
include:
  - _pages

collections:
  artworks:
    output: true
    permalink: /artwork/:slug
    sort_by: position
  p5js:
    output: true
    permalink: /translations/p5js/:slug
  pde:
    output: true
    permalink: /translations/pde/:slug
  artists:
    output: true
    permalink: /artists/:slug/

# defaults values for collections
defaults:
  - scope:
      type: artworks
    values:
      layout: "artwork"
  - scope:
      type: artists
    values:
      layout: "artist"
  - scope:
      type: p5js
    values:
      layout: "p5js"
  - scope:
      type: pde
    values:
      layout: "pde"

minima:
  # Minima skin selection. Available skins are:
  #   Available skins:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized          Adaptive skin for solarized color scheme skins.
  skin: auto

  # Specific pages for site navigation.
  #   If you wish to link only specific pages in the site-navigation, use this and list
  #   the `path` property (as represented via Liquid) of the pages in the order they
  #   should be rendered.
  nav_pages:
    - guide.html
    - translations.html

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: false

  # Minima date format.
  #   The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
  #   Refer to https://shopify.github.io/liquid/filters/date/ for valid values.
  # date_format: "%b-%d-%Y"

  # Social Media Links
  #   Renders icons via Font Awesome Free webfonts CDN, based on ordered list of entries.
  #   Entry keys:
  #     * title    Tooltip rendered on hovering over icon.
  #     * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
  #     * url      Full URL of social profile.
  # social_links:
  #   - title: Minima Theme repository at GitHub
  #     icon: github
  #     url: "https://github.com/jekyll/minima"
  #   - title: Jekyll at X (formerly Twitter)
  #     icon: x-twitter
  #     url: "https://x.com/jekyllrb"

exclude:
  - README.md
  - script/
  - old
  - _plugins
